apiVersion: apps/v1
kind: Deployment
metadata:
  name: visitormgmt-deployment
  namespace: prod
  labels:
    app: visitormgmt
spec:
  replicas: 3  # Number of desired replicas
  selector:
    matchLabels:
      app: visitormgmt
  template:
    metadata:
      labels:
        app: visitormgmt
    spec:
      containers:
        - name: visitormgmt
          image: mahesh541/visitormgmt_v2:latest
          ports:
            - containerPort: 8080
