apiVersion: apps/v1
kind: Deployment
metadata:
  name: visitorservice-deployment
  namespace: dev
  labels:
    app: visitorservice
spec:
  replicas: 1  # Number of desired replicas
  selector:
    matchLabels:
      app: visitorservice
  template:
    metadata:
      labels:
        app: visitorservice
    spec:
      containers:
        - name: visitorservice
          image: mahesh541/visitorservice:latest
          ports:
            - containerPort: 8083
          env: # Setting Enviornmental Variables
            - name: DB_HOST   # Setting Database host address from configMap
              valueFrom:
                configMapKeyRef:
                  name: mylogo-config
                  key: host

            - name: DB_NAME  # Setting Database name from configMap
              valueFrom:
                configMapKeyRef:
                  name: mylogo-config
                  key: dbName

            - name: DB_USERNAME  # Setting Database username from Secret
              valueFrom:
                secretKeyRef:
                  name: mylogo-secrets
                  key: username

            - name: DB_PASSWORD # Setting Database password from Secret
              valueFrom:
                secretKeyRef:
                  name: mylogo-secrets
                  key: password


---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: visitorservice-deployment
  namespace: dev
spec:
  selector:
    app: visitorservice
  ports:
    - protocol: "TCP"
      port: 8083 # The port that the service is running on in the cluster
      targetPort: 8083 # The port exposed by the service
  type: NodePort # type of the service.
