apiVersion: apps/v1
kind: Deployment
metadata:
  name: visitorservice-deployment
  namespace: qa
  labels:
    app: visitorservice
spec:
  replicas: 3  # Number of desired replicas
  selector:
    matchLabels:
      app: visitorservice
  template:
    metadata:
      labels:
        app: visitorservice
    spec:
      containers:
        - name: visitorservice
          image: mahesh541/visitorservice:latest
          ports:
            - containerPort: 8080
