apiVersion: apps/v1
kind: Deployment
metadata:
  name: visitor-service-deployment
  namespace: prod
  labels:
    app: visitor-service
spec:
  replicas: 3  # Number of desired replicas
  selector:
    matchLabels:
      app: visitor-service
  template:
    metadata:
      labels:
        app: visitor-service
    spec:
      containers:
        - name: visitor-service
          image: mahesh541/api-visitor-service:latest
          ports:
            - containerPort: 8080
